apiVersion: v1
kind: Template
metadata:
  name: ${product}-app-template
labels:
  app: default
  createdBy: sbb-it
objects:

  # DEPLOYMENTCONFIG
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${product}
    spec:
      replicas: "${{replicas}}"
      test: false
      selector:
        app: ${product}
        deploymentconfig: ${product}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: ${product}
            deploymentconfig: ${product}
        spec:
          containers:
            - env:
                - name: NEWRELIC_KEY
                  value: ${new_relic_key}
                - name: ${splunk_key}
                  value: ${splunk_index}
                - name: NEWRELIC_APPNAME
                  value: ${product}-${stage}
              image: docker.bin.sbb.ch/${docker_repo}/${product}:${VERSIONTAG}
              imagePullPolicy: Always
              name: ${product}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: ${cpu_min}
                  memory: ${memory_min}
                limits:
                  cpu: ${cpu_max}
                  memory: ${memory_max}
              livenessProbe:
                httpGet:
                  path: ${liveness_probe}
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 30
                periodSeconds: 20
                successThreshold: 1
                failureThreshold: 10
              readinessProbe:
                httpGet:
                  path: ${readyness_probe}
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 60
                timeoutSeconds: 30
                periodSeconds: 20
                successThreshold: 1
                failureThreshold: 10
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
          #  esta: default is a config changeTrigger, not needed
          triggers: {}

  # ROUTE
  - kind: Route
    apiVersion: v1
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      name: ${product}
    spec:
      host: ${product}-${stage}.app.ose.sbb-cloud.net
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: ${product}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Allow

  # SERVICE
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${product}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: ${product}
        deploymentconfig: ${product}
      sessionAffinity: None
      type: ClusterIP

# PARAMETERS
parameters:
  - name: product
    description: product
    required: true
  - name: replicas
    description: Pod Instances Count
    required: true
    value: "1"
  - name: stage
    description: stage
    required: true
  - name: splunk_index
    description: splunk_index
    required: true
  - name: splunk_key
    description: splunk_key met to switch of splunk_key splunk_index_OFF
    required: true
  - name: new_relic_key
    description: new_relic_key
    required: true
  - name: cpu_min
    description: CPU min
    required: true
  - name: cpu_max
    description: CPU max
    required: true
  - name: memory_min
    description: Memory min
    required: true
  - name: memory_max
    description: Memory max
    required: true
  - name: readyness_probe
    description: readyness_probe
    required: true
  - name: liveness_probe
    description: liveness_probe
    required: true
  - name: docker_repo
    description: docker_repo
    required: true
  - name: VERSIONTAG
    description: Selector-Tag for Artifactory
    required: true